# Generated by Django 5.2.4 on 2025-07-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='city',
        ),
        migrations.RemoveField(
            model_name='message',
            name='province',
        ),
    ]
